spring:
  application:
    name: ORDER-SERVICE-9006

server:
  port: 9006

eureka:
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:9000/eureka/
      
security:
  user:
    name: root
    password: root