spring:
  application:
    name: USER-SERVICE-RIBBON-9004

server:
  port: 9004

eureka:
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:9000/eureka/

security:
  user:
    name: root
    password: root