spring:
  application:
    name: ORDER-SERVICE-RIBBON-9007

server:
  port: 9007

eureka:
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:9000/eureka/

security:
  user:
    name: root
    password: root